name: Build and Publish NuGet Package

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Install dependencies
        run: dotnet restore Source/Silverfly/Silverfly.csproj

      - name: Build and package
        run: |
          dotnet build -c Release Source/Silverfly/Silverfly.csproj
          dotnet pack -c Release -o ./nuget Source/Silverfly/Silverfly.csproj
          dotnet build -c Release Source/Silverfly.Testing/Silverfly.Testing.csproj
          dotnet pack -c Release -o ./nuget Source/Silverfly.Testing/Silverfly.Testing.csproj

      - name: Publish to NuGet
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ./nuget/*.nupkg

      - name: Publish package To Nuget
        run: |
          dotnet nuget push ./nuget/*.nupkg --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
